export const items = [
  {
    id: 8,
    title: "فلافل عربية",
    description: "كرات فلافل مقرمشة مع الطحينة.",
    imgUrl: "breakfast.jpg",
    category: "الفطار",
  },
  {
    id: 1,
    title: "برجر لذيذ",
    description: "برجر مشوي مع الجبن والخضار الطازة.",
    imgUrl: "lunch.jpg",
    category: "الغداء",
  },
  {
    id: 2,
    title: "بيتزا إيطالية",
    description: "بيتزا بالجبن والمشروم والريحان الطازة.",
    imgUrl: "dinner.jpg",
    category: "العشاء",
  },
  {
    id: 3,
    title: "شاورما دجاج",
    description: "ساندويتش شاورما دجاج مع صوص الثوم.",
    imgUrl: "lunch.jpg",
    category: "الغداء",
  },
  {
    id: 4,
    title: "سلطة صحية",
    description: "سلطة خضار طازة مع جبنة فيتا وزيت الزيتون.",
    imgUrl: "dinner.jpg",
    category: "العشاء",
  },
  {
    id: 5,
    title: "سوشي ياباني",
    description: "سوشي رولز مع السلمون والأفوكادو.",
    imgUrl: "dinner.jpg",
    category: "العشاء",
  },
  {
    id: 6,
    title: "كباب مشوي",
    description: "أسياخ كباب لحم مشوي مع البصل والفلفل.",
    imgUrl: "lunch.jpg",
    category: "الغداء",
  },
  {
    id: 7,
    title: "باستا كاربونارا",
    description: "مكرونة سباجيتي مع صوص الكريمة والبيكون.",
    imgUrl: "dinner.jpg",
    category: "العشاء",
  },
  {
    id: 8,
    title: "فلافل عربية",
    description: "كرات فلافل مقرمشة مع الطحينة.",
    imgUrl: "breakfast.jpg",
    category: "الفطار",
  },
  {
    id: 9,
    title: "تورتة شوكولاتة",
    description: "كيك شوكولاتة غني ومزين بالكريمة.",
    imgUrl: "breakfast.jpg",
    category: "الفطار",
  },
  {
    id: 10,
    title: "آيس كريم فواكه",
    description: "آيس كريم بطعم الفراولة والمانجا.",
    imgUrl: "dinner.jpg",
    category: "العشاء",
  },
];
